name: Build Chromium Stable

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Set up Git for Windows SDK (full)
        uses: git-for-windows/setup-git-for-windows-sdk@v1
        with:
          install-dir: C:\git-sdk
          flavor: full

      - name: Install Visual Studio Build Tools
        uses: microsoft/setup-msbuild@v2

      - name: Install Depot Tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "$PWD/depot_tools" >> $GITHUB_PATH


      - name: Create chromium directory
        run: mkdir chromium

      - name: Fetch Chromium (without hooks)
        run: |
          cd chromium
          fetch --nohooks chromium


      - name: Run GClient Hooks
        run: |
          cd chromium/src
          gclient runhooks
      - name: Get Latest Stable Version Tag


        id: get_version
        shell: pwsh
        run: |
          $json = Invoke-WebRequest -Uri "https://chromiumdash.appspot.com/releases?platform=Windows" -UseBasicParsing
          $parsed = $json.Content | ConvertFrom-Json
          $stable = $parsed | Where-Object { $_.channel -eq "Stable" } | Select-Object -First 1
          echo "Latest stable version: $($stable.version)"
          echo "::set-output name=version::$($stable.version)"



      - name: Checkout Latest Stable Tag
        run: |
          cd chromium/src
          git fetch --tags
          git checkout tags/${{ steps.get_version.outputs.version }}


      - name: Configure GN Build
        run: |
          cd chromium/src
          gn gen out/Default --args="is_debug=false is_component_build=false"


      - name: Build Chromium (Autoninja)
        run: |
          cd chromium/src
          autoninja -C out/Default chrome


      - name: Package Installer
        run: |
          cd chromium/src
          autoninja -C out/Default mini_installer.exe


      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: chromium-build
          path: chromium/src/out/Default/mini_installer.exe
