name: Chromium Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git python3 build-essential curl lsb-release

    - name: Set up depot_tools
      run: |
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
        echo "$(pwd)/depot_tools" >> $GITHUB_PATH

    - name: Fetch Chromium
      run: |
        mkdir chromium && cd chromium
        fetch --nohooks chromium
        gclient runhooks

    - name: Configure GN
      run: |
        cd chromium/src
        gn gen out/release --args="is_debug=false is_component_build=false use_lld=true use_thin_lto=true thin_lto_enable_optimizations=true"

    - name: Build Chrome
      run: |
        cd chromium/src
        autoninja -C out/release chrome
