name: Build Chromium on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Visual Studio 2022
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild: 'true'
          vc-tools: 'true'
          desktop-workload: 'true'

      - name: Install Windows 11 SDK
        uses: actions/setup-windows-sdk@v1

      - name: Install Depot Tools
        run: |
          $ErrorActionPreference = "Stop"
          Invoke-WebRequest -Uri "https://chromium.googlesource.com/chromium/tools/depot_tools.git" -OutFile "C:\depot_tools.zip"
          Expand-Archive -Path "C:\depot_tools.zip" -DestinationPath "C:\depot_tools"
          [System.Environment]::SetEnvironmentVariable('PATH', $env:PATH + ';C:\depot_tools', [System.EnvironmentVariableTarget]::Machine)

      - name: Get Chrome Stable version from Chromium Dashboard
        id: chrome_version
        run: |
          $ErrorActionPreference = "Stop"
          $response = Invoke-WebRequest -Uri "https://chromiumdash.appspot.com/branches" | ConvertFrom-Json
          $stable_version = ($response.branches | Where-Object { $_.name -eq 'stable' }).head
          Write-Output "Stable Chrome version: $stable_version"
          echo "version=$stable_version" >> $GITHUB_ENV

      - name: Sync depot tools with Chromium version
        run: |
          $ErrorActionPreference = "Stop"
          cd C:\chromium
          .\depot_tools\gclient sync --revision=$env:version

      - name: Install Git
        uses: git-tool-installation-action@v1

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install 7-Zip
        uses: lukasz-wronski/setup-7zip@v1

      - name: Fetch Chromium source code
        run: |
          $ErrorActionPreference = "Stop"
          git clone https://chromium.googlesource.com/chromium/src.git C:\chromium
          cd C:\chromium
          .\depot_tools\gclient sync --revision=$env:version

      - name: Generate build files
        run: |
          $ErrorActionPreference = "Stop"
          cd C:\chromium
          .\depot_tools\gn gen out\Default --args="is_debug=false is_component_build=false"

      - name: Build Chromium
        run: |
          $ErrorActionPreference = "Stop"
          cd C:\chromium
          .\depot_tools\autoninja -C out\Default chrome

      - name: Build installer
        run: |
          $ErrorActionPreference = "Stop"
          cd C:\chromium
          .\depot_tools\autoninja -C out\Default mini_installer.exe

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: chromium-installer
          path: C:\chromium\out\Default\mini_installer.exe
