name: Chromium Windows Stable Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        choco install python --no-progress -y
        choco install git --no-progress -y
        choco install visualstudio2022buildtools --no-progress -y
        python -m pip install --upgrade pip
        python -m pip install pyyaml six psutil setuptools requests
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
        echo "::add-path::$(pwd)/depot_tools"

    - name: Get Stable Version
      run: |
        # Use Python to fetch the stable version from chromiumdash.appspot.com
        python -c "import requests; import json; url = 'https://chromiumdash.appspot.com/branches?format=json'; response = requests.get(url); data = json.loads(response.text); stable_version = next((branch['version'] for branch in data if branch['name'] == 'Stable'), None); print(f'::set-output name=stable_version::{stable_version}')"
      id: get_stable_version

    - name: Configure Environment
      run: |
        echo "DEPOT_TOOLS_WIN_TOOLCHAIN=0" >> $GITHUB_ENV
        echo "GYP_MSVS_VERSION=2022" >> $GITHUB_ENV
        echo "STABLE_VERSION=${{ steps.get_stable_version.outputs.stable_version }}" >> $GITHUB_ENV #set the stable version
        python $(pwd)/depot_tools/gclient.py

    - name: Fetch Chromium Source Code
      run: |
        # Fetch the source code for the stable version.
        python $(pwd)/depot_tools/gclient.py config --unmanaged https://chromium.googlesource.com/chromium/src@${{ env.STABLE_VERSION }}
        python $(pwd)/depot_tools/gclient.py sync

    - name: Build Chromium
      run: |
        cd src
        gn args out\Release "target_os = \"win\"
                               is_debug = false
                               enable_stripping = true" #  customize gn args.
        ninja -C out\Release chrome

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: chromium-stable-build-artifacts
        path: src/out/Release
        retention-days: 1
