name: Build Chromium Windows x64

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Chromium
    runs-on: windows-latest  # For large builds, use a self-hosted runner

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Git and Build Tools
        run: |
          choco install -y git visualstudio2019buildtools visualstudio2019-workload-vctools
          git config --global core.autocrlf false

      - name: Checkout depot_tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "$env:GITHUB_WORKSPACE\depot_tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Fetch Chromium Source
        run: |
          mkdir chromium
          cd chromium
          fetch --nohooks chromium
          cd src
          gclient runhooks

      - name: Configure Build
        run: |
          cd chromium\src
          gn gen out/Default --args="is_debug=false is_component_build=false target_cpu=\"x64\""

      - name: Build Chromium
        run: |
          cd chromium\src
          autoninja -C out/Default chrome

      - name: Archive Chromium Output
        run: |
          cd chromium\src\out\Default
          Compress-Archive -Path chrome.exe,*.dll,*.pak,locales -DestinationPath $env:GITHUB_WORKSPACE\chromium_build.zip

      - name: Upload Chromium Artifact
        uses: actions/upload-artifact@v4
        with:
          name: chromium-windows-x64
          path: chromium_build.zip
