name: Build Chromium with LTO and O3

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted  # Use self-hosted Windows runner
    steps:
    - name: Set up Git
      run: git config --global core.autocrlf false

    - name: Install Depot Tools
      run: |
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
        echo "$env:GITHUB_WORKSPACE\depot_tools" >> $env:GITHUB_PATH

    - name: Fetch Chromium Source
      run: |
        mkdir chromium && cd chromium
        fetch --nohooks chromium
        cd src
        gclient runhooks

    - name: Set up Build Config with LTO and O3
      run: |
        cd chromium/src
        gn gen out/Default --args="is_debug=false is_component_build=false symbol_level=0 enable_nacl=false is_official_build=true use_lld=true chrome_pgo_phase=0 use_thin_lto=true use_lto=true is_clang=true clang_use_chrome_plugins=false treat_warnings_as_errors=false dcheck_always_on=false target_cpu=\"x64\""
        echo 'cflags = [ "-O3" ]' >> out/Default/args.gn
        echo 'ldflags = [ "-O3" ]' >> out/Default/args.gn
        gn gen out/Default

    - name: Build Chromium
      run: |
        cd chromium/src
        autoninja -C out/Default chrome
